config/routes.rb
Company::Application.routes.draw do
  namespace :spree do
    resources :locations
  end

  namespace :spree do
    resources :companies
  end

end

app/models/spree.rb
module Spree
  def self.table_name_prefix
    'spree_'
  end
end

app/models/spree/company.rb
class Spree::Company < ActiveRecord::Base
  attr_accessible :contact, :email, :logo, :name, :phone, :website
  attr_accessible :locations_attributes
  
  has_many :locations
  accepts_nested_attributes_for :locations,
                                :allow_destroy => true
                                
 # validates_associated :locations                              
  
end

app/models/spree/location.rb
class Spree::Location < ActiveRecord::Base
  belongs_to :company
  attr_accessible :address, :city, :company_id, :email, :fax, :latitude, :longitude, :phone, :postal_code, :state, :website
  

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/spree/companies_controller.rb
class Spree::CompaniesController < ApplicationController
  # GET /spree/companies
  # GET /spree/companies.json
  def index
    @spree_companies = Spree::Company.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @spree_companies }
    end
  end

  # GET /spree/companies/1
  # GET /spree/companies/1.json
  def show
    @spree_company = Spree::Company.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @spree_company }
    end
  end

  # GET /spree/companies/new
  # GET /spree/companies/new.json
  def new
    @spree_company = Spree::Company.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @spree_company }
    end
  end

  # GET /spree/companies/1/edit
  def edit
    @spree_company = Spree::Company.find(params[:id])
  end

  # POST /spree/companies
  # POST /spree/companies.json
  def create
    @spree_company = Spree::Company.new(params[:spree_company])

    respond_to do |format|
      if @spree_company.save
        format.html { redirect_to @spree_company, notice: 'Company was successfully created.' }
        format.json { render json: @spree_company, status: :created, location: @spree_company }
      else
        format.html { render action: "new" }
        format.json { render json: @spree_company.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /spree/companies/1
  # PUT /spree/companies/1.json
  def update
    @spree_company = Spree::Company.find(params[:id])

    respond_to do |format|
      if @spree_company.update_attributes(params[:spree_company])
        format.html { redirect_to @spree_company, notice: 'Company was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @spree_company.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /spree/companies/1
  # DELETE /spree/companies/1.json
  def destroy
    @spree_company = Spree::Company.find(params[:id])
    @spree_company.destroy

    respond_to do |format|
      format.html { redirect_to spree_companies_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/spree/locations_controller.rb
class Spree::LocationsController < ApplicationController
  # GET /spree/locations
  # GET /spree/locations.json
  def index
    @spree_locations = Spree::Location.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @spree_locations }
    end
  end

  # GET /spree/locations/1
  # GET /spree/locations/1.json
  def show
    @spree_location = Spree::Location.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @spree_location }
    end
  end

  # GET /spree/locations/new
  # GET /spree/locations/new.json
  def new
    @spree_location = Spree::Location.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @spree_location }
    end
  end

  # GET /spree/locations/1/edit
  def edit
    @spree_location = Spree::Location.find(params[:id])
  end

  # POST /spree/locations
  # POST /spree/locations.json
  def create
    @spree_location = Spree::Location.new(params[:spree_location])

    respond_to do |format|
      if @spree_location.save
        format.html { redirect_to @spree_location, notice: 'Location was successfully created.' }
        format.json { render json: @spree_location, status: :created, location: @spree_location }
      else
        format.html { render action: "new" }
        format.json { render json: @spree_location.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /spree/locations/1
  # PUT /spree/locations/1.json
  def update
    @spree_location = Spree::Location.find(params[:id])

    respond_to do |format|
      if @spree_location.update_attributes(params[:spree_location])
        format.html { redirect_to @spree_location, notice: 'Location was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @spree_location.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /spree/locations/1
  # DELETE /spree/locations/1.json
  def destroy
    @spree_location = Spree::Location.find(params[:id])
    @spree_location.destroy

    respond_to do |format|
      format.html { redirect_to spree_locations_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/spree/companies_helper.rb
module Spree::CompaniesHelper
end

app/helpers/spree/locations_helper.rb
module Spree::LocationsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Company</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/spree/companies/_form.html.erb
<%= form_for(@spree_company) do |f| %>
  <% if @spree_company.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@spree_company.errors.count, "error") %> prohibited this spree_company from being saved:</h2>

      <ul>
      <% @spree_company.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :contact %><br />
    <%= f.text_field :contact %>
  </div>
  <div class="field">
    <%= f.label :phone %><br />
    <%= f.text_field :phone %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :website %><br />
    <%= f.text_field :website %>
  </div>
  <div class="field">
    <%= f.label :logo %><br />
    <%= f.text_field :logo %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/spree/companies/_location_fields.html.erb
<div id="new-location-fields" class="modal fade" data-backdrop="static">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
    <h3>Add a Location<%= " to the #{ @vompany.name } Location list" unless @company.name.nil? %></h3>
  </div>
  <div class="modal-body">
    <fieldset>
      <div class="control-group">
        <%= f.label(:address, :class => "control-label") %>
        <div class="controls">
          <%= f.text_field(:address, :class => "input-xlarge field") %>
        </div>
      </div>

      <div class="control-group">
        <%= f.label(:city, :class => "control-label") %>
        <div class="controls">
          <%= f.text_field(:city, :class => "input-xlarge field") %>
        </div>
      </div>
     
      <div class="control-group">
        <%= f.label(:state, :class => "control-label") %>
        <div class="controls">
          <%= f.text_field(:state, :class => "input-xlarge field") %>
        </div>
      </div>
      
      <div class="control-group">
        <%= f.label(:country, :class => "control-label") %>
        <div class="controls">
          <%= f.text_field(:country, :class => "input-xlarge field", :data => { :validation => "required validate_length length2-50", "validation-error-msg" => "Country is required and cannot be must be between 2 and 50 characters." }) %>
        </div>
      </div>
    
     
      <div class="control-group">
        <%= f.label(:postal_code, :class => "control-label") %>
        <div class="controls">
          <%= f.text_field(:postal_code, :class => "input-xlarge field") %>
        </div>
      </div>
     
      <div class="control-group">
        <%= f.label(:phone, :class => "control-label") %>
        <div class="controls">
          <%= f.text_field(:phone, :class => "input-xlarge field") %>
        </div>
      </div>
     
      <div class="control-group">
        <%= f.label(:email, :class => "control-label") %>
        <div class="controls">
          <%= f.text_field(:email, :class => "input-xlarge field") %>
        </div>
      </div>
     
      <div class="control-group">
        <%= f.label(:website, :class => "control-label") %>
        <div class="controls">
          <%= f.text_field(:website, :class => "input-xlarge field") %>
        </div>
      </div>
     
      <div class="control-group">
        <%= f.label(:latitude, :class => "control-label") %>
        <div class="controls">
          <%= f.text_field(:latitude, :class => "input-xlarge field") %>
        </div>
      </div>
     
      <div class="control-group">
        <%= f.label(:longitude, :class => "control-label") %>
        <div class="controls">
          <%= f.text_field(:longitude, :class => "input-xlarge field") %>
        </div>
      </div>
     
      <div class="control-group">
        <%= f.label(:manager, :class => "control-label") %>
        <div class="controls">
          <%= f.text_field(:manager, :class => "input-xlarge field") %>
        </div>
      </div>
      
    
    
    
    
      <%= f.hidden_field(:_destroy, :class => "field") %>
    </fieldset>
  </div>
  <div class="modal-footer">
    <button id="addButton" type="button" class="btn btn-primary" data-dismiss="modal" aria-hidden="true" title="Add this Pilot to the list of Pilots that are assigned to this Ship.">Add</button>
    <button id="cancelButton" type="button" class="btn btn-inverse" data-dismiss="modal" aria-hidden="true" title="Close this screen without adding the Pilot to the list.">Cancel</button>
  </div>
</div>

<script type="text/javascript">
  pilotFieldsUI.init();
</script>

app/views/spree/companies/_locations_display.html.erb
<table id="locations-display-table" class="table table-hover table-striped">
  <thead>
      <th>Address</th>
      <th>City</th>
      <th>State</th>
      <th>Country</th>
      <th>Postal Code</th>
      <th>Phone</th>
      <th>Fax</th>
      <th>e-mail</th>
      <th>Website</th>
      <th>Latitude</th>
      <th>Longitude</th>
      <th>Manager</th>
                  
  </thead>
  <tbody>
      <% @company.locations.each do |pilot| %>
          <tr class="fields">
            <td><%= company.address %></td>
            <td><%= company.city %></td>
            <td><%= company.state %></td>
            <td><%= company.country %></td>
            <td><%= company.postal_code %></td>
            <td><%= company.phone %></td>
            <td><%= company.fax %></td>
            <td><%= company.emai %></td>
            <td><%= company.website %></td>
            <td><%= company.latitude %></td>
            <td><%= company.longitude %></td>
            <td><%= company.manager %></td>
          </tr>
      <% end %>
  </tbody>
</table>

app/views/spree/companies/_locations_table.html.erb
<table id="pilots-table" class="table table-hover table-striped">
  <thead>
    <th>First Name</th>
    <th>Last Name</th>
    <th>Call Sign</th>
  <th></th>
  </thead>
  <tbody>
    <%= f.fields_for(:pilots) do |pilots_form| %>
      <tr class="fields">
        <td><%= pilots_form.text_field(:first_name) %></td>
        <td><%= pilots_form.text_field(:last_name) %></td>
        <td><%= pilots_form.text_field(:call_sign) %></td>
        <%# if current_page?(new_ship_path) || current_page?(edit_ship_path) %>
            <td>
              <%= link_to_remove_fields('<i class="icon-remove"></i>'.html_safe, pilots_form, :title => "Delete this Pilot.") %>
            </td>
        <%# end %>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/spree/companies/_pilot_fields.html.erb
<div id="new-pilot-fields" class="modal fade" data-backdrop="static">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
    <h3>Add a Pilot<%= " to the #{ @ship.name } Pilot Roster" unless @ship.name.nil? %></h3>
  </div>
  <div class="modal-body">
    <fieldset>
      <div class="control-group">
        <%= f.label(:first_name, :class => "control-label") %>
        <div class="controls">
          <%= f.text_field(:first_name, :class => "input-xlarge field", :data => { :validation => "required validate_max_length length50", "validation-error-msg" => "First Name is required and cannot be longer than 50 characters." }) %>
        </div>
      </div>

      <div class="control-group">
        <%= f.label(:last_name, :class => "control-label") %>
        <div class="controls">
          <%= f.text_field(:last_name, :class => "input-xlarge field", :data => { :validation => "required validate_max_length length50", "validation-error-msg" => "Last Name is required and cannot be longer than 50 characters." }) %>
        </div>
      </div>

      <div class="control-group">
        <%= f.label(:call_sign, :class => "control-label") %>
        <div class="controls">
          <%= f.text_field(:call_sign, :class => "input-xlarge field", :data => { :validation => "required validate_length length5-50", "validation-error-msg" => "Call Sign is required and cannot be must be between 5 and 50 characters." }) %>
        </div>
      </div>
      <%= f.hidden_field(:_destroy, :class => "field") %>
    </fieldset>
  </div>
  <div class="modal-footer">
    <button id="addButton" type="button" class="btn btn-primary" data-dismiss="modal" aria-hidden="true" title="Add this Pilot to the list of Pilots that are assigned to this Ship.">Add</button>
    <button id="cancelButton" type="button" class="btn btn-inverse" data-dismiss="modal" aria-hidden="true" title="Close this screen without adding the Pilot to the list.">Cancel</button>
  </div>
</div>

<script type="text/javascript">
  pilotFieldsUI.init();
</script>

app/views/spree/companies/_pilots_table.html.erb
<table id="pilots-table" class="table table-hover table-striped">
  <thead>
    <th>First Name</th>
    <th>Last Name</th>
    <th>Call Sign</th>
  <th></th>
  </thead>
  <tbody>
    <%= f.fields_for(:pilots) do |pilots_form| %>
      <tr class="fields">
        <td><%= pilots_form.text_field(:first_name) %></td>
        <td><%= pilots_form.text_field(:last_name) %></td>
        <td><%= pilots_form.text_field(:call_sign) %></td>
        <%# if current_page?(new_ship_path) || current_page?(edit_ship_path) %>
            <td>
              <%= link_to_remove_fields('<i class="icon-remove"></i>'.html_safe, pilots_form, :title => "Delete this Pilot.") %>
            </td>
        <%# end %>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/spree/companies/edit.html.erb
<h1>Editing spree_company</h1>

<%= render 'form' %>

<%= link_to 'Show', @spree_company %> |
<%= link_to 'Back', spree_companies_path %>

app/views/spree/companies/index.html.erb
<h1>Listing spree_companies</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Contact</th>
    <th>Phone</th>
    <th>Email</th>
    <th>Website</th>
    <th>Logo</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @spree_companies.each do |spree_company| %>
  <tr>
    <td><%= spree_company.name %></td>
    <td><%= spree_company.contact %></td>
    <td><%= spree_company.phone %></td>
    <td><%= spree_company.email %></td>
    <td><%= spree_company.website %></td>
    <td><%= spree_company.logo %></td>
    <td><%= link_to 'Show', spree_company %></td>
    <td><%= link_to 'Edit', edit_spree_company_path(spree_company) %></td>
    <td><%= link_to 'Destroy', spree_company, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Company', new_spree_company_path %>

app/views/spree/companies/new.html.erb
<h1>New spree_company</h1>

<%= render 'form' %>

<%= link_to 'Back', spree_companies_path %>

app/views/spree/companies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @spree_company.name %>
</p>

<p>
  <b>Contact:</b>
  <%= @spree_company.contact %>
</p>

<p>
  <b>Phone:</b>
  <%= @spree_company.phone %>
</p>

<p>
  <b>Email:</b>
  <%= @spree_company.email %>
</p>

<p>
  <b>Website:</b>
  <%= @spree_company.website %>
</p>

<p>
  <b>Logo:</b>
  <%= @spree_company.logo %>
</p>


<%= link_to 'Edit', edit_spree_company_path(@spree_company) %> |
<%= link_to 'Back', spree_companies_path %>

app/views/spree/locations/_form.html.erb
<%= form_for(@spree_location) do |f| %>
  <% if @spree_location.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@spree_location.errors.count, "error") %> prohibited this spree_location from being saved:</h2>

      <ul>
      <% @spree_location.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :company_id %><br />
    <%= f.number_field :company_id %>
  </div>
  <div class="field">
    <%= f.label :address %><br />
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :city %><br />
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label :state %><br />
    <%= f.text_field :state %>
  </div>
  <div class="field">
    <%= f.label :country %><br />
    <%= f.text_field :country %>
  </div>
  <div class="field">
    <%= f.label :postal_code %><br />
    <%= f.text_field :postal_code %>
  </div>
  <div class="field">
    <%= f.label :phone %><br />
    <%= f.text_field :phone %>
  </div>
  <div class="field">
    <%= f.label :fax %><br />
    <%= f.text_field :fax %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :website %><br />
    <%= f.text_field :website %>
  </div>
  <div class="field">
    <%= f.label :latitude %><br />
    <%= f.text_field :latitude %>
  </div>
  <div class="field">
    <%= f.label :longitude %><br />
    <%= f.text_field :longitude %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/spree/locations/edit.html.erb
<h1>Editing spree_location</h1>

<%= render 'form' %>

<%= link_to 'Show', @spree_location %> |
<%= link_to 'Back', spree_locations_path %>

app/views/spree/locations/index.html.erb
<h1>Listing spree_locations</h1>

<table>
  <tr>
    <th>Company</th>
    <th>Address</th>
    <th>City</th>
    <th>State</th>
    <th>Country</th>
    <th>Postal code</th>
    <th>Phone</th>
    <th>Fax</th>
    <th>Email</th>
    <th>Website</th>
    <th>Latitude</th>
    <th>Longitude</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @spree_locations.each do |spree_location| %>
  <tr>
    <td><%= spree_location.company_id %></td>
    <td><%= spree_location.address %></td>
    <td><%= spree_location.city %></td>
    <td><%= spree_location.state %></td>
    <td><%= spree_location.country %></td>
    <td><%= spree_location.postal_code %></td>
    <td><%= spree_location.phone %></td>
    <td><%= spree_location.fax %></td>
    <td><%= spree_location.email %></td>
    <td><%= spree_location.website %></td>
    <td><%= spree_location.latitude %></td>
    <td><%= spree_location.longitude %></td>
    <td><%= link_to 'Show', spree_location %></td>
    <td><%= link_to 'Edit', edit_spree_location_path(spree_location) %></td>
    <td><%= link_to 'Destroy', spree_location, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Location', new_spree_location_path %>

app/views/spree/locations/new.html.erb
<h1>New spree_location</h1>

<%= render 'form' %>

<%= link_to 'Back', spree_locations_path %>

app/views/spree/locations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Company:</b>
  <%= @spree_location.company_id %>
</p>

<p>
  <b>Address:</b>
  <%= @spree_location.address %>
</p>

<p>
  <b>City:</b>
  <%= @spree_location.city %>
</p>

<p>
  <b>State:</b>
  <%= @spree_location.state %>
</p>

<p>
  <b>Country:</b>
  <%= @spree_location.country %>
</p>

<p>
  <b>Postal code:</b>
  <%= @spree_location.postal_code %>
</p>

<p>
  <b>Phone:</b>
  <%= @spree_location.phone %>
</p>

<p>
  <b>Fax:</b>
  <%= @spree_location.fax %>
</p>

<p>
  <b>Email:</b>
  <%= @spree_location.email %>
</p>

<p>
  <b>Website:</b>
  <%= @spree_location.website %>
</p>

<p>
  <b>Latitude:</b>
  <%= @spree_location.latitude %>
</p>

<p>
  <b>Longitude:</b>
  <%= @spree_location.longitude %>
</p>


<%= link_to 'Edit', edit_spree_location_path(@spree_location) %> |
<%= link_to 'Back', spree_locations_path %>